# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Syntax-Highlight-JSON
version:      0.01
version_from: lib/Syntax/Highlight/JSON.pm
installdirs:  site
requires:
    Carp:                          0
    IO::File:                      0
    IO::Scalar:                    0
    JSON::Streaming::Reader:       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
